# INSTALL DOCKER
# Check docker
- shell: docker -v
  register: bindocker
  ignore_errors: true

- debug:
    msg: "{{bindocker}}"

# - shell: echo "1"
#   register: localdockerversion 
#   when: bindocker.stdout | regex_search('(?i)docker') | first
#   ignore_errors: true

# - shell: echo "0"
#   register: localdockerversion 
#   when: bindocker.stdout==""
#   ignore_errors: true

- name: docker is present?
  fail: msg="Detected {{bindocker.stdout}}"
  when: bindocker.stdout!=""
  ignore_errors: true


# INSTALL DOCKER
- block:
  #- template:
  #    src: "{{playbook_dir}}/roles/playkubo/templates/install-docker.sh"
  #    dest: /home/pi/install-docker.sh
  #    owner: pi
  #    mode: 0775

  - name: Install Docker
    register: outdocker
    shell: curl -sSL https://get.docker.com | sh
    #/home/pi/install-docker.sh
    #ignore_errors: true

  - debug: var=outdocker.stdout_lines

  when: bindocker.stdout==""

  # RESTART DOCKER
- block:

  - name: Set pi user group docker
    become: true
    become_method: sudo
    shell: usermod -aG docker pi
    register: dockeruser
    ignore_errors: true 

  - debug: msg="{{ dockeruser.stdout }}"
    ignore_errors: true

  - name: Stop Docker
    become: true
    become_method: sudo
    register: stopoutdocker
    shell: /etc/init.d/docker stop

  - debug: var=stopoutdocker.stdout_lines

  - name: Start Docker
    become: true
    become_method: sudo
    register: startoutdocker
    shell: /etc/init.d/docker start

  - debug: var=startoutdocker.stdout_lines

  - name: Stopping all docker containers
    become: true
    become_method: sudo
    shell: docker stop $(docker ps -a -q)
    register: dockerstop
    ignore_errors: true 
  
  - debug: msg="{{ dockerstop.stdout }}"
    ignore_errors: true

  - name: Removing all docker containers
    become: true
    become_method: sudo
    shell: docker rm $(docker ps -a -q)
    register: dockerremove
    ignore_errors: true

  - debug: msg="{{ dockerremove.stdout }}"
    ignore_errors: true

  # - name: Enable docker at boot
  #   become: true
  #   become_method: sudo
  #   shell: sudo systemctl enable docker
  #   register: dockerenable
  #   ignore_errors: true

  # - debug: msg="{{ dockerenable.stdout }}"
  #   ignore_errors: true
  #when: hostvars['PLAYKUBO'].bindocker.stdout!=""